# Generated by Django 3.1.7 on 2021-02-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('boleta', models.CharField(max_length=200)),
                ('nom_usuario', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
