# Generated by Django 3.1.7 on 2021-02-26 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_auto_20210226_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='nom_usuario',
            new_name='clave',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='fecha',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='password',
            new_name='nombre_usuario',
        ),
    ]
