# Generated by Django 3.1.7 on 2021-03-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0004_control_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_ubicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_entrada', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Qrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.CharField(max_length=200)),
                ('fecha_hora_caducidad', models.CharField(max_length=200)),
            ],
        ),
    ]
