# Generated by Django 3.1.7 on 2021-03-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0005_historial_ubicaciones_qrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
            ],
        ),
    ]
