# Generated by Django 3.1.7 on 2021-03-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0007_salones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='qrs',
            name='qr',
        ),
        migrations.AddField(
            model_name='qrs',
            name='codigo_barras',
            field=models.ImageField(blank=True, upload_to='barcodes/'),
        ),
    ]
