# Generated by Django 3.1.7 on 2021-04-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0009_auto_20210302_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrs',
            name='codigo_barras',
            field=models.ImageField(blank=True, upload_to='qr_code'),
        ),
    ]
