# Generated by Django 3.1.7 on 2021-04-03 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoreo', '0010_auto_20210401_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrs',
            old_name='fecha_hora_caducidad',
            new_name='nombre_usuario',
        ),
    ]
