# Generated by Django 3.1.7 on 2021-04-03 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0011_auto_20210402_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrs',
            old_name='codigo_barras',
            new_name='url',
        ),
    ]
