# Generated by Django 3.1.7 on 2021-04-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0014_auto_20210428_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id_tipo',
            field=models.IntegerField(default=1),
        ),
    ]
