# Generated by Django 3.1.7 on 2021-04-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0015_auto_20210428_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='boleta',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
