# Generated by Django 3.1.7 on 2021-04-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0016_auto_20210428_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='boleta',
            field=models.CharField(default='Invitado', max_length=200),
        ),
    ]
