# Generated by Django 3.1.7 on 2021-04-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0017_auto_20210428_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restringidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sintomas', models.CharField(max_length=200)),
                ('condicion', models.CharField(max_length=200)),
                ('fecha_prueba', models.DateField(max_length=200)),
                ('tipo_prueba', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Historial_ubicaciones',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='curp',
            field=models.CharField(default=1621, max_length=200),
            preserve_default=False,
        ),
    ]
