# Generated by Django 3.1.7 on 2021-04-30 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoreo', '0018_auto_20210430_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restringidos',
            old_name='condicion',
            new_name='estado_condicion',
        ),
        migrations.AddField(
            model_name='restringidos',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
