# Generated by Django 3.1.7 on 2021-05-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0020_control_usuarios_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
