# Generated by Django 3.1.7 on 2021-05-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0021_usuarios_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
