# Generated by Django 3.1.7 on 2021-05-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0022_usuarios_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control_usuarios',
            name='user',
        ),
        migrations.AddField(
            model_name='control_usuarios',
            name='nombre_usuario',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
