# Generated by Django 3.1.7 on 2021-05-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0023_auto_20210503_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='control_usuarios',
            old_name='oxigeno',
            new_name='oxigenacion',
        ),
    ]
