# Generated by Django 3.1.7 on 2021-05-05 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoreo', '0024_auto_20210504_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='control_usuarios',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='control_usuarios',
            name='fecha_hora_registro',
            field=models.DateField(max_length=200),
        ),
    ]
