# Generated by Django 3.1.7 on 2021-05-05 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0025_auto_20210504_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control_usuarios',
            name='nombre_usuario',
        ),
    ]
