# Generated by Django 3.1.7 on 2021-05-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0026_auto_20210505_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='restringidos',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
