# Generated by Django 3.1.7 on 2021-05-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0026_remove_control_usuarios_nombre_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='control_usuarios',
            name='nombre_usuario',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
