# Generated by Django 3.1.7 on 2021-05-05 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoreo', '0027_control_usuarios_nombre_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control_usuarios',
            name='user',
        ),
        migrations.AddField(
            model_name='control_usuarios',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
