# Generated by Django 3.1.7 on 2021-05-05 04:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoreo', '0028_auto_20210504_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_usuarios',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
