# Generated by Django 3.1.7 on 2021-05-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0028_remove_restringidos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restringidos',
            name='estado_condicion',
            field=models.IntegerField(default=1),
        ),
    ]
