# Generated by Django 3.1.7 on 2021-05-05 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoreo', '0029_auto_20210504_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control_usuarios',
            name='user',
        ),
        migrations.AddField(
            model_name='control_usuarios',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
